/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package devolucionesYPrestamos;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author DAM114
 */
public class devoluciones extends javax.swing.JDialog {

    
    private daoClasesSQL.PrestamoDAO pDAO = new daoClasesSQL.PrestamoDAO();
    private javax.swing.DefaultListModel<Object[]> modeloLista = new javax.swing.DefaultListModel<>();

    public devoluciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarPrestamosPendientes(); 
        configurarEventos();
    }
    private void cargarPrestamosPendientes() {
        modeloLista.clear();
        // Llamamos al nuevo método que trae todos
        List<Object[]> todos = pDAO.listarTodosLosPrestamos();

        for (Object[] p : todos) {
            modeloLista.addElement(p);
        }
        jList1.setModel(modeloLista);

        jList1.setCellRenderer(new javax.swing.DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                if (value instanceof Object[]) {
                    Object[] p = (Object[]) value;
                    String id = p[0].toString();
                    String usuario = p[1].toString();
                    String material = p[2].toString();
                    String cant = p[3].toString();
                    Object fechaDev = p[4]; // Aquí está la clave

                    if (fechaDev == null) {
                        // Si no hay fecha, está PENDIENTE
                        setText("<html><b style='color:red;'>[PENDIENTE]</b> ID: " + id + " | " + usuario + " - " + material + " (" + cant + ")</html>");
                    } else {
                        // Si hay fecha, está DEVUELTO
                        setText("<html><b style='color:green;'>[OK - DEVUELTO]</b> ID: " + id + " | " + usuario + " - " + material + "</html>");
                        // Opcional: Desactivar visualmente los devueltos para que no intentes clicar
                        if (!isSelected) setForeground(java.awt.Color.GRAY);
                    }
                }
                return this;
            }
        });
    }
    
    private void configurarEventos() {
    // BOTÓN: Marcar como devuelto
    jButton3.addActionListener(evt -> ejecutarDevolucion());
    
    // BOTÓN: Salir
    jButton1.addActionListener(evt -> dispose());
    
    // NOTA: Si tenías código en jButton2, bórralo o ignóralo, ya no lo usaremos.
    }
    private void ejecutarDevolucion() {
        Object[] seleccionado = (Object[]) jList1.getSelectedValue();

        if (seleccionado == null) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un préstamo de la lista.");
            return;
        }

        // Comprobamos si ya está devuelto (posición 4 del array)
        if (seleccionado[4] != null) {
            JOptionPane.showMessageDialog(this, "Este material ya fue devuelto anteriormente.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idPrestamo = (int) seleccionado[0];
        String material = (String) seleccionado[2];

        int confirmar = JOptionPane.showConfirmDialog(this, 
                "¿Confirmar la devolución de: " + material + "?", 
                "Confirmar Devolución", JOptionPane.YES_NO_OPTION);

        if (confirmar == JOptionPane.YES_OPTION) {
            // Ejecutamos la lógica en la BD
            if (pDAO.registrarDevolucion(idPrestamo)) {
                JOptionPane.showMessageDialog(this, "¡Éxito! El stock ha sido actualizado.");

                // RECARGA: Esto hará que el CellRenderer lo pinte en VERDE
                cargarPrestamosPendientes(); 
                jList1.repaint(); 
            } else {
                JOptionPane.showMessageDialog(this, "Error: No se pudo registrar la devolución.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Devoluciones");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Listado de devoluciones");

        jScrollPane2.setViewportView(jList1);

        jButton3.setText("Marcar como devuelto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(131, 131, 131)
                        .addComponent(jButton1)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(219, 219, 219))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ejecutarDevolucion();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                devoluciones dialog = new devoluciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
