/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package devolucionesYPrestamos;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelClasesTablas.Prestamo;

/**
 *
 * @author DAM114
 */
public class prestamos extends javax.swing.JDialog {

    private modelClasesTablas.Usuario userLogueado;
    private List<Prestamo> registroPrestamos = new ArrayList<>();
    private javax.swing.DefaultListModel<Object[]> modeloLista = new javax.swing.DefaultListModel<>();
    private daoClasesSQL.MaterialDAO mDAO = new daoClasesSQL.MaterialDAO();
    
   

    class Material {
        String nombre;
        int stock;
        boolean prestable;

        public Material(String nombre, int stock, boolean prestable) {
            this.nombre = nombre;
            this.stock = stock;
            this.prestable = prestable;
        }

        @Override
        public String toString() {
            return nombre + " (Stock: " + stock + ")";
        }
    }
    
    class Prestamo {
        String persona;
        Material material;
        int cantidad;
        LocalDate fecha;

        public Prestamo(String persona, Material material, int cantidad, LocalDate fecha) {
            this.persona = persona;
            this.material = material;
            this.cantidad = cantidad;
            this.fecha = fecha;
            
        }
    }
    /**
     * Creates new form prestamos
     */
    public prestamos(java.awt.Frame parent, boolean modal, modelClasesTablas.Usuario usuarioQueVieneDelLogin) {
    super(parent, modal);
    this.userLogueado = usuarioQueVieneDelLogin; 
    
    initComponents();
    
    if (this.userLogueado != null) {
        // LLAMADA CORREGIDA: Pasamos ID (int), Nombre (String) y Rol (String)
        cargarUsuarios(
            userLogueado.getId_usuario(), 
            userLogueado.getNombre(), 
            userLogueado.getRol()
        );
    }
    
    inicializarDatos();
    configurarEventos();
    cargarMateriales();
}

    private void inicializarDatos() {
        // Cargar materiales de ejemplo en la lista
       

        // Reemplazar el modelo por defecto generado por NetBeans
        jList1.setModel((javax.swing.ListModel) modeloLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
<<<<<<< Updated upstream
        jSeparator1 = new javax.swing.JSeparator();
=======
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxUsuarios = new javax.swing.JComboBox<>();
>>>>>>> Stashed changes

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(76, 76, 76));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Préstamos");

        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Solicitar prestamo");

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Observaciones");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
<<<<<<< Updated upstream
                        .addComponent(jButton1)
                        .addGap(35, 35, 35)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
=======
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
>>>>>>> Stashed changes
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
<<<<<<< Updated upstream
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
=======
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 87, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
>>>>>>> Stashed changes
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cargarMateriales() {
        modeloLista.clear();
        
        // Usamos tu MaterialDAO para buscar los materiales disponibles en la BD
        java.util.List<Object[]> materiales = mDAO.buscar("", "", "disponible", "");
        for (Object[] m : materiales) {
            modeloLista.addElement(m);
        }
        jList1.setModel(modeloLista);
        
        // Esto le da formato a la lista para que leas el nombre en vez del código de memoria
        jList1.setCellRenderer(new javax.swing.DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Object[]) {
                    Object[] m = (Object[]) value;
                    setText(m[1] + " (Stock: " + m[6] + ")"); // Muestra el nombre y la cantidad
                }
                return this;
            }
        });
    }
    
    
    private void configurarEventos() {
        // Evento para el botón "Solicitar prestamo" (jButton1)
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarPrestamo();
            }
        });

        // Evento para cancelar/cerrar
        jButton3.addActionListener(evt -> dispose());
    }

    // --- 3. LÓGICA DEL PRÉSTAMO CON BASE DE DATOS ---
    private void realizarPrestamo() {
        Object[] seleccionado = (Object[]) jList1.getSelectedValue();

<<<<<<< Updated upstream
        // Validaciones básicas
        if (nombrePersona.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar el nombre de la persona.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
=======
        Object[] materialSel = (Object[]) jList1.getSelectedValue();
        Object[] usuarioSel = (Object[]) jComboBoxUsuarios.getSelectedItem(); // Obtenemos el usuario del combo
        
>>>>>>> Stashed changes
        if (seleccionado == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un material.");
            return;
        }

<<<<<<< Updated upstream
        // Extraemos los datos del array seleccionado (según el orden de tu MaterialDAO)
        int idMaterial = (int) seleccionado[0];
        String nombreMaterial = (String) seleccionado[1];
        String estadoMaterial = (String) seleccionado[4];
        int stockActual = (int) seleccionado[6];

        // Validar que el material se pueda prestar (Estado 'disponible')
        if (!estadoMaterial.equalsIgnoreCase("disponible")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Este material no está habilitado para préstamos (Estado: " + estadoMaterial + ").", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar stock (Criterio: Actualiza estado o stock)
        if (stockActual <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay stock disponible para este material.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
=======
    int idUsuario = (int) usuarioSel[0];   // El ID real
        String nombreUser = usuarioSel[1].toString(); // El nombre

        String cantTexto = jTextField2.getText().trim();
        String obsTexto  = jTextField3.getText().trim();

        try {
            int idMat = (int) materialSel[0];
            int stock = (int) materialSel[6];
            int cantPedida = Integer.parseInt(cantTexto);
>>>>>>> Stashed changes

        // Lógica de cantidad (Asumimos 1 por defecto)
        int cantidadSolicitada = 1;

<<<<<<< Updated upstream
        // Crear el objeto Préstamo usando TU constructor
        // OJO: He puesto 'null' en el Estado. Si tu Enum requiere un valor, ponlo aquí (ej. Estado.PRESTADO)
        modelClasesTablas.Prestamo nuevoPrestamo = new modelClasesTablas.Prestamo(
                idMaterial, 
                nombrePersona, 
                "Préstamo de " + nombreMaterial, 
                null, // <--- Tu clase Estado
                cantidadSolicitada, 
                "Sin observaciones"
        );
=======
            // Creamos el objeto Préstamo con el nombre del usuario seleccionado
            modelClasesTablas.Prestamo p = new modelClasesTablas.Prestamo(
                    idMat, nombreUser, "Préstamo", null, cantPedida, obsTexto
            );
>>>>>>> Stashed changes

        // Guardar en la Base de Datos
        daoClasesSQL.PrestamoDAO pDAO = new daoClasesSQL.PrestamoDAO();

<<<<<<< Updated upstream
        if (pDAO.registrarPrestamo(nuevoPrestamo)) {
            // Confirmación
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Préstamo registrado con éxito a " + nombrePersona + "\nMaterial: " + nombreMaterial, 
                    "Éxito", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            // Limpiar formulario
            jTextField1.setText("");
            jList1.clearSelection();
            
            // ¡IMPORTANTE! Refrescamos la lista llamando a la BD para ver el stock actualizado
            cargarMateriales(); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el préstamo en la base de datos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
=======
            // Guardamos usando el idUsuario que sacamos del combo
            if (pDAO.registrarPrestamo(p, idUsuario)) {
                JOptionPane.showMessageDialog(this, "¡Préstamo realizado con éxito!");
                cargarMateriales(); // Refrescar stock en la lista
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número.");
>>>>>>> Stashed changes
        }
    }

            // Asegúrate de que los parámetros sean: int, String, String
    private void cargarUsuarios(int idActual, String nombreActual, String rolActual) {
        jComboBoxUsuarios.removeAllItems(); // Limpiar el combo

        if (rolActual.equalsIgnoreCase("administrador")) {
            // Si es admin, traemos todos de la base de datos
            daoClasesSQL.UsuarioDAO uDAO = new daoClasesSQL.UsuarioDAO();
            java.util.List<Object[]> usuarios = uDAO.listarUsuarios();
            for (Object[] u : usuarios) {
                jComboBoxUsuarios.addItem(u); 
            }
        } else {
            // Si es profesor, solo se agrega a sí mismo (mismo formato que el admin: ID, Nombre, Rol)
            Object[] yo = new Object[]{idActual, nombreActual, rolActual};
            jComboBoxUsuarios.addItem(yo);
        }

        // Configurar el Renderer para mostrar el nombre
        jComboBoxUsuarios.setRenderer(new javax.swing.DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Object[]) {
                    Object[] u = (Object[]) value;
                    setText(u[1].toString()); // El nombre está en la posición 1
                }
                return this;
            }
        });
    }

    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        // Creamos un usuario temporal para que el programa no de error al probar
        modelClasesTablas.Usuario testUser = new modelClasesTablas.Usuario();
        testUser.setNombre("Admin");
        testUser.setRol("administrador");

        // PASAMOS EL TERCER PARÁMETRO AQUÍ:
        prestamos dialog = new prestamos(new javax.swing.JFrame(), true, testUser);
        dialog.setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<Object[]> jComboBoxUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
<<<<<<< Updated upstream
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
=======
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
>>>>>>> Stashed changes
    // End of variables declaration//GEN-END:variables
}


    

