/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package devolucionesYPrestamos;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author DAM114
 */
public class prestamos extends javax.swing.JDialog {

    private List<Prestamo> registroPrestamos = new ArrayList<>();
    private javax.swing.DefaultListModel<Object[]> modeloLista = new javax.swing.DefaultListModel<>();
    private daoClasesSQL.MaterialDAO mDAO = new daoClasesSQL.MaterialDAO();
    
   

    class Material {
        String nombre;
        int stock;
        boolean prestable;

        public Material(String nombre, int stock, boolean prestable) {
            this.nombre = nombre;
            this.stock = stock;
            this.prestable = prestable;
        }

        @Override
        public String toString() {
            return nombre + " (Stock: " + stock + ")";
        }
    }
    
    class Prestamo {
        String persona;
        Material material;
        int cantidad;
        LocalDate fecha;

        public Prestamo(String persona, Material material, int cantidad, LocalDate fecha) {
            this.persona = persona;
            this.material = material;
            this.cantidad = cantidad;
            this.fecha = fecha;
        }
    }
    /**
     * Creates new form prestamos
     */
    public prestamos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarDatos();
        configurarEventos();
    }

    private void inicializarDatos() {
        // Cargar materiales de ejemplo en la lista
       

        // Reemplazar el modelo por defecto generado por NetBeans
        jList1.setModel((javax.swing.ListModel) modeloLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Prestamos");

        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Solicitar prestamo");

        jButton2.setText("Aceptar");

        jButton3.setText("Cancelar");

        jLabel2.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(68, 68, 68)
                .addComponent(jButton3)
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarMateriales() {
        modeloLista.clear();
        
        // Usamos tu MaterialDAO para buscar los materiales disponibles en la BD
        java.util.List<Object[]> materiales = mDAO.buscar("", "", "disponible", "");
        for (Object[] m : materiales) {
            modeloLista.addElement(m);
        }
        jList1.setModel(modeloLista);
        
        // Esto le da formato a la lista para que leas el nombre en vez del código de memoria
        jList1.setCellRenderer(new javax.swing.DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Object[]) {
                    Object[] m = (Object[]) value;
                    setText(m[1] + " (Stock: " + m[6] + ")"); // Muestra el nombre y la cantidad
                }
                return this;
            }
        });
    }
    
    
    private void configurarEventos() {
        // Evento para el botón "Solicitar prestamo" (jButton1)
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarPrestamo();
            }
        });

        // Evento para cancelar/cerrar
        jButton3.addActionListener(evt -> dispose());
    }

    // --- 3. LÓGICA DEL PRÉSTAMO CON BASE DE DATOS ---
    private void realizarPrestamo() {
        String nombrePersona = jTextField1.getText().trim();
        
        // Ahora la lista devuelve un array de objetos con los datos de la BD
        Object[] seleccionado = (Object[]) jList1.getSelectedValue();

        // Validaciones básicas
        if (nombrePersona.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar el nombre de la persona.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (seleccionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un material de la lista.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Extraemos los datos del array seleccionado (según el orden de tu MaterialDAO)
        int idMaterial = (int) seleccionado[0];
        String nombreMaterial = (String) seleccionado[1];
        String estadoMaterial = (String) seleccionado[4];
        int stockActual = (int) seleccionado[6];

        // Validar que el material se pueda prestar (Estado 'disponible')
        if (!estadoMaterial.equalsIgnoreCase("disponible")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Este material no está habilitado para préstamos (Estado: " + estadoMaterial + ").", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar stock (Criterio: Actualiza estado o stock)
        if (stockActual <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay stock disponible para este material.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lógica de cantidad (Asumimos 1 por defecto)
        int cantidadSolicitada = 1;

        // Crear el objeto Préstamo usando TU constructor
        // OJO: He puesto 'null' en el Estado. Si tu Enum requiere un valor, ponlo aquí (ej. Estado.PRESTADO)
        modelClasesTablas.Prestamo nuevoPrestamo = new modelClasesTablas.Prestamo(
                idMaterial, 
                nombrePersona, 
                "Préstamo de " + nombreMaterial, 
                null, // <--- Tu clase Estado
                cantidadSolicitada, 
                "Sin observaciones"
        );

        // Guardar en la Base de Datos
        daoClasesSQL.PrestamoDAO pDAO = new daoClasesSQL.PrestamoDAO();

        if (pDAO.registrarPrestamo(nuevoPrestamo)) {
            // Confirmación
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Préstamo registrado con éxito a " + nombrePersona + "\nMaterial: " + nombreMaterial, 
                    "Éxito", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            // Limpiar formulario
            jTextField1.setText("");
            jList1.clearSelection();
            
            // ¡IMPORTANTE! Refrescamos la lista llamando a la BD para ver el stock actualizado
            cargarMateriales(); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el préstamo en la base de datos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                prestamos dialog = new prestamos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}


    

