/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package devolucionesYPrestamos;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelClasesTablas.Prestamo;

/**
 * Ventana modal para tramitar la salida de materiales del taller de
 * informática. Controla que los profesores solo puedan pedirse cosas a sí
 * mismos y que el administrador gestione a todos.
 *
 * * @author aday fernandez
 */
public class prestamos extends javax.swing.JDialog {

    private List<Prestamo> registroPrestamos = new ArrayList<>();
    private javax.swing.DefaultListModel<Object[]> modeloLista = new javax.swing.DefaultListModel<>();
    private daoClasesSQL.MaterialDAO mDAO = new daoClasesSQL.MaterialDAO();
    private modelClasesTablas.Usuario userLogueado;

    /**
     * Clase interna para simular la estructura de los materiales de la
     * aplicacion.
     */
    class Material {

        String nombre;
        int stock;
        boolean prestable;

        public Material(String nombre, int stock, boolean prestable) {
            this.nombre = nombre;
            this.stock = stock;
            this.prestable = prestable;
        }

        @Override
        public String toString() {
            return nombre + " (Stock: " + stock + ")";
        }
    }

    /**
     * Clase interna para estructurar un modelo local de prestamos en memoria.
     */
    class Prestamo {

        String persona;
        Material material;
        int cantidad;
        LocalDate fecha;

        public Prestamo(String persona, Material material, int cantidad, LocalDate fecha) {
            this.persona = persona;
            this.material = material;
            this.cantidad = cantidad;
            this.fecha = fecha;

        }
    }

    /**
     * Constructor que inicia la gestion de prestamos cargando el usuario activo
     * y los materiales.
     *
     * * @param parent ventana principal de la interfaz que posee este dialogo.
     * @param modal bloquea las acciones de la ventana principal si esta en
     * true.
     * @param usuarioQueViene datos completos del profesor o admin que ha
     * iniciado la sesion.
     */
    public prestamos(java.awt.Frame parent, boolean modal, modelClasesTablas.Usuario usuarioQueViene) {
        super(parent, modal);
        this.userLogueado = usuarioQueViene; // Guardamos la sesión antes que nada
        initComponents();

        // Cargamos los usuarios usando los datos del que inició sesión
        cargarUsuarios(userLogueado.getId_usuario(), userLogueado.getNombre(), userLogueado.getRol());

        cargarMateriales();
        configurarEventos();
    }

    /**
     * Vincula el modelo dinámico al JList generado por NetBeans.
     */
    private void inicializarDatos() {
        // Cargar materiales de ejemplo en la lista

        // Reemplazar el modelo por defecto generado por NetBeans
        jList1.setModel((javax.swing.ListModel) modeloLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxUsuarios = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(76, 76, 76));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Préstamos");

        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Solicitar prestamo");

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Observaciones");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxUsuarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 87, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * Recupera los materiales que tienen estado disponible en AWS y los añade
     * al JList. Aplica un formateador personalizado para extraer el texto de
     * las filas de la consulta.
     */
    private void cargarMateriales() {
        modeloLista.clear();

        // Usamos tu MaterialDAO para buscar los materiales disponibles en la BD
        java.util.List<Object[]> materiales = mDAO.buscar("", "", "disponible", "");
        for (Object[] m : materiales) {
            modeloLista.addElement(m);
        }
        jList1.setModel(modeloLista);

        // Esto le da formato a la lista para que leas el nombre en vez del código de memoria
        jList1.setCellRenderer(new javax.swing.DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Object[]) {
                    Object[] m = (Object[]) value;
                    setText(m[1] + " (Stock: " + m[6] + ")"); // Muestra el nombre y la cantidad
                }
                return this;
            }
        });
    }

    /**
     * Asocia los botones físicos de la pantalla con sus métodos lógicos.
     */
    private void configurarEventos() {
        // Evento para el botón "Solicitar prestamo" (jButton1)
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarPrestamo();
            }
        });

        // Evento para cancelar/cerrar
        jButton3.addActionListener(evt -> dispose());
    }

    /**
     * Valida los campos de texto y procesa el préstamo definitivo a través del
     * PrestamoDAO. Controla las excepciones de formato y recarga los datos de
     * stock si todo sale bien.
     */
   private void realizarPrestamo() {
    Object[] matSel = (Object[]) jList1.getSelectedValue();
    Object[] userSel = (Object[]) jComboBoxUsuarios.getSelectedItem();

    if (matSel == null || userSel == null) {
        JOptionPane.showMessageDialog(this, "Selecciona material y usuario.");
        return;
    }

    try {
        int idUsuario = (int) userSel[0]; // ID real de la base de datos
        String nombreUser = userSel[1].toString();
        int idMat = (int) matSel[0];
        
        // 1. Validar que el campo de texto no esté vacío y sea un número válido
        String textoCantidad = jTextField2.getText().trim();
        if (textoCantidad.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa una cantidad.");
            return;
        }
        
        int cantPedida = Integer.parseInt(textoCantidad);

        // 2. Validar que no pidan 0 o cantidades negativas
        if (cantPedida <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad pedida debe ser mayor a 0.");
            return;
        }

        // 3. OBTENER Y VALIDAR EL STOCK DISPONIBLE
        // Usamos .toString() y ParseInt para evitar errores de casteo según el tipo de dato que devuelva la BD
        int stockDisponible = Integer.parseInt(matSel[6].toString()); 

        if (cantPedida > stockDisponible) {
            JOptionPane.showMessageDialog(this, 
                "No puedes pedir más unidades de las disponibles.\nStock actual: " + stockDisponible, 
                "Stock Insuficiente", 
                JOptionPane.WARNING_MESSAGE);
            return; // Detiene el proceso si no hay suficiente stock
        }

        // Si pasa todas las validaciones, procedemos con el préstamo
        modelClasesTablas.Prestamo p = new modelClasesTablas.Prestamo(
                idMat, nombreUser, "Préstamo", null, cantPedida, jTextField3.getText().trim()
        );

        daoClasesSQL.PrestamoDAO pDAO = new daoClasesSQL.PrestamoDAO();
        if (pDAO.registrarPrestamo(p, idUsuario)) { // Guardamos con el ID correcto
            JOptionPane.showMessageDialog(this, "¡Éxito!");
            cargarMateriales(); // Recarga la lista actualizando el stock visual
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La cantidad debe ser un número entero válido.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

    /**
     * Rellena el combo de usuarios según el rol del usuario que ha iniciado
     * sesión. Si es administrador se cargan todos los usuarios de la base de
     * datos, si es profesor solo él mismo.
     *
     * * @param idActual el identificador numérico de la cuenta activa.
     * @param nombreActual el nombre del profesor logueado.
     * @param rolActual el grupo o nivel de permisos (administrador o profesor).
     */
    private void cargarUsuarios(int idActual, String nombreActual, String rolActual) {
        jComboBoxUsuarios.removeAllItems();

        if (rolActual.equalsIgnoreCase("administrador")) {
            daoClasesSQL.UsuarioDAO uDAO = new daoClasesSQL.UsuarioDAO();
            List<Object[]> usuarios = uDAO.listarUsuarios();
            for (Object[] u : usuarios) {
                jComboBoxUsuarios.addItem(u);
            }
        } else {
            // El profesor solo se ve a sí mismo
            jComboBoxUsuarios.addItem(new Object[]{idActual, nombreActual, rolActual});
        }

        // Renderer para mostrar solo el nombre en el Combo
        jComboBoxUsuarios.setRenderer(new javax.swing.DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Object[]) {
                    Object[] u = (Object[]) value;
                    setText(u[1].toString()); // Posición 1 es el nombre
                }
                return this;
            }
        });
    }

    /**
     * Lanza la ventana de pruebas simulando un inicio de sesion administrador
     * por defecto.
     *
     * * @param args argumentos de ejecucion de la linea de comandos.
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                // Creamos un usuario "fantasma" para que el main no dé error al compilar
                modelClasesTablas.Usuario userTest = new modelClasesTablas.Usuario();
                userTest.setId_usuario(1);
                userTest.setNombre("Prueba");
                userTest.setRol("administrador");

                // SOLUCIÓN: Pasamos el tercer parámetro (userTest)
                prestamos dialog = new prestamos(new javax.swing.JFrame(), true, userTest);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<Object[]> jComboBoxUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
