/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewFormularios;

import daoClasesSQL.CategoriaDAO;
import daoClasesSQL.MaterialDAO;
import daoClasesSQL.UbicacionDAO;
import java.util.List;
import javax.swing.JOptionPane;
import modelClasesTablas.Categoria;
import modelClasesTablas.Estado;
import modelClasesTablas.Material;
import modelClasesTablas.Ubicacion;

/**
 *
 * @author DAM125
 */
public class FormularioAltaMaterial extends javax.swing.JDialog {

    /**
     * Creates new form FormularioAltaMaterial
     */
    public FormularioAltaMaterial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Nuevo material");
        cargarDatosIniciales();
        
    }
    
    //Metodo creado para cargar los datos de los desplegables
    private void cargarDatosIniciales(){
        desplegableEstado.removeAllItems();
        desplegableEstado.addItem("Seleccione el estado del producto.");
        desplegableEstado.addItem("Disponible");
        desplegableEstado.addItem("Prestado");
        desplegableEstado.addItem("Reparacion");
        desplegableEstado.addItem("Baja");
        
        desplegableCategoria.removeAllItems();
        CategoriaDAO categorias = new CategoriaDAO();
        List<Categoria> listaCategorias = categorias.listarTodos();
        
        for (Categoria categoria : listaCategorias) {
            desplegableCategoria.addItem(categoria);
        }
        
        desplegableUbicacion.removeAllItems();
        UbicacionDAO ubicacion = new UbicacionDAO();
        List<Ubicacion> ubicaciones = ubicacion.listarTodos();
        
        for (Ubicacion ubi : ubicaciones) {
            desplegableUbicacion.addItem(ubi);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lineaSeparador1 = new javax.swing.JSeparator();
        etiquetaNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        lineaSeparador2 = new javax.swing.JSeparator();
        etiquetaDescripcion = new javax.swing.JLabel();
        campoDescripcion = new javax.swing.JTextField();
        etiquetaCantidad = new javax.swing.JLabel();
        selectorCantidad = new javax.swing.JSpinner();
        etiquetaEstado = new javax.swing.JLabel();
        desplegableEstado = new javax.swing.JComboBox<>();
        desplegableCategoria = new javax.swing.JComboBox<>();
        etiquetaCategoria = new javax.swing.JLabel();
        etiquetaUbicacion = new javax.swing.JLabel();
        desplegableUbicacion = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Introduce los datos del componente");

        lineaSeparador1.setForeground(new java.awt.Color(255, 255, 255));

        etiquetaNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaNombre.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaNombre.setText("Nombre:");

        lineaSeparador2.setForeground(new java.awt.Color(255, 255, 255));

        etiquetaDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaDescripcion.setText("Descripcion:");

        etiquetaCantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaCantidad.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaCantidad.setText("Cantidad:");

        selectorCantidad.setModel(new javax.swing.SpinnerNumberModel(0, null, 1000, 1));

        etiquetaEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaEstado.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaEstado.setText("Estado:");

        desplegableEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        desplegableEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegableEstadoActionPerformed(evt);
            }
        });

        desplegableCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegableCategoriaActionPerformed(evt);
            }
        });

        etiquetaCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaCategoria.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaCategoria.setText("Categoria:");

        etiquetaUbicacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaUbicacion.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaUbicacion.setText("Ubicacion:");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lineaSeparador2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lineaSeparador1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaNombre)
                            .addComponent(etiquetaDescripcion)
                            .addComponent(etiquetaCantidad)
                            .addComponent(etiquetaEstado)
                            .addComponent(etiquetaCategoria)
                            .addComponent(etiquetaUbicacion))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNombre)
                            .addComponent(campoDescripcion)
                            .addComponent(desplegableEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(desplegableCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(selectorCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 156, Short.MAX_VALUE))
                            .addComponent(desplegableUbicacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineaSeparador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDescripcion)
                    .addComponent(campoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCantidad)
                    .addComponent(selectorCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaEstado)
                    .addComponent(desplegableEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desplegableCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCategoria))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaUbicacion)
                    .addComponent(desplegableUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(lineaSeparador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void desplegableEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegableEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegableEstadoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void desplegableCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegableCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegableCategoriaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        String nombre = campoNombre.getText().trim();
        
        if (nombre.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor añade un nombre", "Campo vacío", javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
        String descripcion = campoDescripcion.getText().trim();
        int cantidad = (int) selectorCantidad.getValue();
        Categoria cat = (Categoria) desplegableCategoria.getSelectedItem();
        Ubicacion ubi = (Ubicacion) desplegableUbicacion.getSelectedItem();
        String estado = (String) desplegableEstado.getSelectedItem();
        
        Material nuevoMaterial = new Material(nombre,descripcion,cantidad, estado,cat.getId_categoria(),ubi.getId_ubicacion());
        MaterialDAO dao = new MaterialDAO();
        dao.insertarMaterial(nuevoMaterial);
        javax.swing.JOptionPane.showMessageDialog(this, "¡Material guardado correctamente!");
        this.dispose();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioAltaMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioAltaMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioAltaMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioAltaMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioAltaMaterial dialog = new FormularioAltaMaterial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField campoDescripcion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JComboBox<Categoria> desplegableCategoria;
    private javax.swing.JComboBox<String> desplegableEstado;
    private javax.swing.JComboBox<Ubicacion> desplegableUbicacion;
    private javax.swing.JLabel etiquetaCantidad;
    private javax.swing.JLabel etiquetaCategoria;
    private javax.swing.JLabel etiquetaDescripcion;
    private javax.swing.JLabel etiquetaEstado;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaUbicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator lineaSeparador1;
    private javax.swing.JSeparator lineaSeparador2;
    private javax.swing.JSpinner selectorCantidad;
    // End of variables declaration//GEN-END:variables
}
