/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewFormularios;

import daoClasesSQL.CategoriaDAO;
import daoClasesSQL.EstadoDAO;
import daoClasesSQL.MaterialDAO;
import daoClasesSQL.UbicacionDAO;
import java.util.List;
import javax.swing.JOptionPane;
import modelClasesTablas.Categoria;
import modelClasesTablas.Estado;
import modelClasesTablas.Material;
import modelClasesTablas.Ubicacion;

/**
 *
 * @author David Alonso Casaiz
 */
public class FormularioAltaMaterialNuevo extends javax.swing.JDialog {

    /**
     * Creates new form FormularioAltaMaterial
     */
    public FormularioAltaMaterialNuevo(java.awt.Frame parent, boolean modal) {
        //LLamada al constructor de la ventana padre, el modal sirve para que la ventana
        //principal quede bloqueada mientras la de alta esta activa
        super(parent, modal);
        //Inicializa todos los componentes del formulario
        initComponents();
        //Nombre de la ventana del material
        this.setTitle("Nuevo material");
        //Llamamos al metodo privado para cargar todos los datos iniciales de la base de datos
        //Necesarios para el formulario
        cargarDatosIniciales();

    }
    
    
    
    //Metodo creado para cargar los datos de los desplegables
    private void cargarDatosIniciales() {
        //Al iniciar el metodo vaciamos el desplegable del estado
        //Para asegurarnos de que cuando se recojan los datos no haya duplicados
        desplegableEstado.removeAllItems();
        
        //Hacemos una instancia del DAO de estado y lo metemos en una lista usando el metodo para listar todos los elementos
        EstadoDAO estadoDAO = new daoClasesSQL.EstadoDAO();
        List<Estado> listaEstados = estadoDAO.listarTodos();
        
        //Recorremos la lista y por cada uno de ellos anadimos al desplegable los datos que estan en la base de datos
        //De esta manera al usuario siempre le apareceran los tipos de estado que hay en la base de datos
        for (Estado est : listaEstados) {
            desplegableEstado.addItem(est);
        }
        
        //Volvemos a eliminar el contenido esta vez de categoria, por el mismo motivo que el estado
        desplegableCategoria.removeAllItems();
        
        //Instanciamos el DAO de categoria y lo anadimos a su lista
        CategoriaDAO categorias = new CategoriaDAO();
        List<Categoria> listaCategorias = categorias.listarTodos();
        
        //Recorremos y anadimos cada categoria al desplegable
        for (Categoria categoria : listaCategorias) {
            desplegableCategoria.addItem(categoria);
        }
        
        
        //Instanciamos el DAO de ubicacion y lo metemos en una lista
        UbicacionDAO ubicacionDAO = new UbicacionDAO();
        desplegableArmario.removeAllItems();
        
        for (String armario : ubicacionDAO.listarArmarios()) {
            
            desplegableArmario.addItem(armario);
            
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lineaSeparador1 = new javax.swing.JSeparator();
        etiquetaNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        lineaSeparador2 = new javax.swing.JSeparator();
        etiquetaDescripcion = new javax.swing.JLabel();
        campoDescripcion = new javax.swing.JTextField();
        etiquetaCantidad = new javax.swing.JLabel();
        selectorCantidad = new javax.swing.JSpinner();
        etiquetaEstado = new javax.swing.JLabel();
        desplegableEstado = new javax.swing.JComboBox<>();
        desplegableCategoria = new javax.swing.JComboBox<>();
        etiquetaCategoria = new javax.swing.JLabel();
        etiquetaArmario = new javax.swing.JLabel();
        desplegableArmario = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        etiquetaCajon = new javax.swing.JLabel();
        desplegableCajon = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(76, 76, 76));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Introduce los datos del componente");

        lineaSeparador1.setForeground(new java.awt.Color(153, 153, 153));

        etiquetaNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaNombre.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaNombre.setText("Nombre:");

        lineaSeparador2.setForeground(new java.awt.Color(153, 153, 153));

        etiquetaDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaDescripcion.setText("Descripcion:");

        etiquetaCantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaCantidad.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaCantidad.setText("Cantidad:");

        selectorCantidad.setModel(new javax.swing.SpinnerNumberModel(0, null, 1000, 1));

        etiquetaEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaEstado.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaEstado.setText("Estado:");

        desplegableEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegableEstadoActionPerformed(evt);
            }
        });

        desplegableCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegableCategoriaActionPerformed(evt);
            }
        });

        etiquetaCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaCategoria.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaCategoria.setText("Categoria:");

        etiquetaArmario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaArmario.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaArmario.setText("Armario");

        desplegableArmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegableArmarioActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        etiquetaCajon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaCajon.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaCajon.setText("Cajon:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaNombre)
                            .addComponent(etiquetaDescripcion)
                            .addComponent(etiquetaCantidad)
                            .addComponent(etiquetaEstado)
                            .addComponent(etiquetaCategoria)
                            .addComponent(etiquetaArmario)
                            .addComponent(etiquetaCajon))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoDescripcion)
                            .addComponent(desplegableEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(desplegableCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(selectorCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(desplegableArmario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoNombre)
                            .addComponent(desplegableCajon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 28, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lineaSeparador2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15))
                                .addComponent(lineaSeparador1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineaSeparador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDescripcion)
                    .addComponent(campoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCantidad)
                    .addComponent(selectorCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaEstado)
                    .addComponent(desplegableEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desplegableCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCategoria))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaArmario)
                    .addComponent(desplegableArmario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCajon)
                    .addComponent(desplegableCajon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(lineaSeparador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void desplegableEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegableEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegableEstadoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //Cerramos la ventana de alta y volvemos a la ventana principal
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void desplegableCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegableCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegableCategoriaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //Recibimos el nombre recogido en el campo del nombre del material al que dar de alta
        String nombre = campoNombre.getText().trim();

        //En caso de que el usuario no incluya un nombre, se lo pediremos
        if (nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor añade un nombre", "Campo vacío", javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            //Recogemos los datos que nos da el usuario sobre el material que quiere dar de alta en la aplicacion y en la base de datos.
            String descripcion = campoDescripcion.getText().trim();
            int cantidad = (int) selectorCantidad.getValue();
            Categoria cat = (Categoria) desplegableCategoria.getSelectedItem();
            Ubicacion ubi = (Ubicacion) desplegableArmario.getSelectedItem();
            Estado estado = (Estado) desplegableEstado.getSelectedItem();
            
            //Creamos un nuevo material en base a los datos recogidos del formulario
            Material nuevoMaterial = new Material(nombre, descripcion, cantidad, estado.getId_estado(), cat.getId_categoria(), ubi.getId_ubicacion());
            
            // Creamos el DAO para gestionar el acceso a la base de datos
            MaterialDAO dao = new MaterialDAO();
            
            //Insertamos el nuevo material en la base de datos
            dao.insertarMaterial(nuevoMaterial);
            
            javax.swing.JOptionPane.showMessageDialog(this, "¡Material guardado correctamente!");
            //Volvemos a la ventana princial.
            this.dispose();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void desplegableArmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegableArmarioActionPerformed
        String armarioSeleccionado = (String) desplegableArmario.getSelectedItem();
        
        if (armarioSeleccionado == null){
            return;
        }
        
        desplegableCajon.removeAllItems();
        
        UbicacionDAO ubicacionDAO = new UbicacionDAO();
        
        for (Ubicacion ubi : ubicacionDAO.listarCajonesPorArmario(armarioSeleccionado)) {
            desplegableCajon.addItem(ubi);
        }
        
    }//GEN-LAST:event_desplegableArmarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioAltaMaterialNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioAltaMaterialNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioAltaMaterialNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioAltaMaterialNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioAltaMaterialNuevo dialog = new FormularioAltaMaterialNuevo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField campoDescripcion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JComboBox<String> desplegableArmario;
    private javax.swing.JComboBox<Ubicacion> desplegableCajon;
    private javax.swing.JComboBox<Categoria> desplegableCategoria;
    private javax.swing.JComboBox<Estado> desplegableEstado;
    private javax.swing.JLabel etiquetaArmario;
    private javax.swing.JLabel etiquetaCajon;
    private javax.swing.JLabel etiquetaCantidad;
    private javax.swing.JLabel etiquetaCategoria;
    private javax.swing.JLabel etiquetaDescripcion;
    private javax.swing.JLabel etiquetaEstado;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator lineaSeparador1;
    private javax.swing.JSeparator lineaSeparador2;
    private javax.swing.JSpinner selectorCantidad;
    // End of variables declaration//GEN-END:variables
}
