/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewFormularios;

import daoClasesSQL.CategoriaDAO;
import daoClasesSQL.MaterialDAO;
import daoClasesSQL.UbicacionDAO;
import java.awt.Desktop;
import java.io.File;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelClasesTablas.Categoria;
import modelClasesTablas.Estado;
import modelClasesTablas.Material;
import modelClasesTablas.Ubicacion;

/**
 *
 * @author DAM126
 */
public class VentanaBusqueda extends javax.swing.JDialog {

    /**
     * Creates new form VentanaBusqueda
     */
    public VentanaBusqueda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Busqueda Componentes");
        this.setLocationRelativeTo(null);

        // 1. Categorías: Añadir "TODAS" al principio
        ElejirCategoria.removeAllItems();
        ElejirCategoria.addItem("TODAS");
        CategoriaDAO categoriaDAO = new CategoriaDAO();
        for (Categoria c : categoriaDAO.listarTodos()) {
            ElejirCategoria.addItem(c.getNombre());
        }

        // 2. Estados: Ya lo tienes bien encaminado
        ElejirEstado.removeAllItems();
        ElejirEstado.addItem("TODOS");
        daoClasesSQL.EstadoDAO estadoDAO = new daoClasesSQL.EstadoDAO();
        for (modelClasesTablas.Estado e : estadoDAO.listarTodos()) {
            ElejirEstado.addItem(e.getNombre());
        }

        // 3. Armarios — carga solo los unicos
        ElejirArmario.removeAllItems();
        ElejirArmario.addItem("TODOS");
        UbicacionDAO ubicacionDAO = new UbicacionDAO();
        List<Ubicacion> ubicaciones = ubicacionDAO.listarTodos();

        Set<String> armariosUnicos = new java.util.LinkedHashSet<>();
        for (Ubicacion u : ubicaciones) {
            armariosUnicos.add(u.getUbicacion()); 
        }
        for (String armario : armariosUnicos) {
            ElejirArmario.addItem(armario);
        }

        // 4. Cajon empieza vacio
        ElejirCajon.removeAllItems();
        ElejirCajon.addItem("TODOS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botonBuscar = new javax.swing.JButton();
        Categoria = new javax.swing.JLabel();
        ElejirCategoria = new javax.swing.JComboBox<>();
        ElejirCajon = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ElejirEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TextBusqueda = new javax.swing.JTextField();
        MensageMaterialesEncontrados = new javax.swing.JLabel();
        BotonCancelar = new javax.swing.JButton();
        Armario = new javax.swing.JLabel();
        ElejirArmario = new javax.swing.JComboBox<>();
        Cajon = new javax.swing.JLabel();
        BotonPaginaWeb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(76, 76, 76));

        jPanel1.setBackground(new java.awt.Color(76, 76, 76));

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        Categoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Categoria.setForeground(new java.awt.Color(255, 255, 255));
        Categoria.setText("Categoría:");

        ElejirCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElejirCategoriaActionPerformed(evt);
            }
        });

        ElejirCajon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estado:");

        ElejirEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "disponible", "prestado", "reparacion", "baja" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripción", "Categoría", "Estado", "ubicacion", "Cantidad"
            }
        ));
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        TextBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBusquedaActionPerformed(evt);
            }
        });

        MensageMaterialesEncontrados.setForeground(new java.awt.Color(255, 255, 255));

        BotonCancelar.setText("Cancelar");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        Armario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Armario.setForeground(new java.awt.Color(255, 255, 255));
        Armario.setText("Armario");

        ElejirArmario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ElejirArmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElejirArmarioActionPerformed(evt);
            }
        });

        Cajon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cajon.setForeground(new java.awt.Color(255, 255, 255));
        Cajon.setText("Cajon");

        BotonPaginaWeb.setText("Ir Pagina Web");
        BotonPaginaWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPaginaWebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cajon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ElejirCajon, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ElejirEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Armario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ElejirArmario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ElejirCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(62, 62, 62)
                        .addComponent(TextBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BotonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(MensageMaterialesEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonPaginaWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Categoria)
                    .addComponent(ElejirCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Armario)
                            .addComponent(ElejirArmario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ElejirCajon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cajon))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ElejirEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(MensageMaterialesEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(BotonPaginaWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)
                            .addComponent(BotonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:

        try {

            String texto = TextBusqueda.getText().trim();
            String categoriaSel = (String) ElejirCategoria.getSelectedItem();
            String estadoSel = (String) ElejirEstado.getSelectedItem();
            String armarioSel = (String) ElejirArmario.getSelectedItem();
            String cajonSel = (String) ElejirCajon.getSelectedItem();

            // Integer idCategoria = null;
//            if (categoriaSel != null && !categoriaSel.equals("TODAS")) {  // ✅ Cambiar a categoriaSel
//                for (Categoria c : new CategoriaDAO().listarTodos()) {
//                    if (c.getNombre().equals(categoriaSel)) {
//                        idCategoria = c.getId_categoria();
//                    }
//                }
//            }
//
//            String estado = null;
//            if (estadoSel != null && !estadoSel.equals("TODOS")) {
//                estado = estadoSel.toLowerCase();
//            }
//
//            Integer idUbicacion = null;
//            if (ubicacionSel != null && !ubicacionSel.equals("TODAS")) {  // ← Cambiar a ubicacionSel
//                for (Ubicacion u : new UbicacionDAO().listarTodos()) {
//                    String ubicacionStr = u.getArmario() + " - " + u.getBalda();
//                    if (ubicacionStr.equals(ubicacionSel)) {
//                        idUbicacion = u.getId_ubicacion();
//                    }
//                }
//            }
            String textoFiltro = texto.isEmpty() ? null : texto;
            String categoriaFiltro = (categoriaSel != null && categoriaSel.equals("TODAS")) ? null : categoriaSel;
            String estadoFiltro = (estadoSel != null && estadoSel.equals("TODOS")) ? null : estadoSel;
            String ubicacionFiltro = null;
            
            // Combinar armario y cajon para el filtro de ubicacion
            if (armarioSel != null && !armarioSel.equals("TODOS")) {
                if (cajonSel != null && !cajonSel.equals("TODOS")) {
                    ubicacionFiltro = armarioSel + " - " + cajonSel.replace("Cajon ", "");
                } else {
                    ubicacionFiltro = armarioSel;
                }
            }

            MaterialDAO dao = new MaterialDAO();
            List<Object[]> lista = dao.buscar(textoFiltro, categoriaFiltro, estadoFiltro, ubicacionFiltro);

            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);
            for (Object[] fila : lista) {
                modelo.addRow(new Object[]{
                    fila[1],
                    fila[2],
                    fila[3],
                    fila[4],
                    fila[5],
                    fila[6]});

            }

            if (lista.isEmpty()) {
                MensageMaterialesEncontrados.setText("No se encontraron materiales");
            } else if (lista.size() == 1) {
                MensageMaterialesEncontrados.setText("1 material encontrado");
            } else {
                MensageMaterialesEncontrados.setText(lista.size() + " materiales encontrados");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al buscar: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void TextBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBusquedaActionPerformed

    private void ElejirCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElejirCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElejirCategoriaActionPerformed

    private void botonBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_botonCancelarActionPerformed

    private void BotonPaginaWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPaginaWebActionPerformed
        // TODO add your handling code here:
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().browse(
                        new URI("http://3.224.141.230/")
                );
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo abrir la pagina web");
        }

    }//GEN-LAST:event_BotonPaginaWebActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void ElejirArmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElejirArmarioActionPerformed
        // TODO add your handling code here:
        String armarioSel = (String) ElejirArmario.getSelectedItem();
        ElejirCajon.removeAllItems();
        ElejirCajon.addItem("TODOS");

        if (armarioSel == null || armarioSel.equals("TODOS")) {
            return;
        }

        UbicacionDAO ubicacionDAO = new UbicacionDAO();
        for (Ubicacion u : ubicacionDAO.listarTodos()) {
            if (u.getUbicacion().equals(armarioSel)) {
                String cajon = (u.getCajon() != null) ? "Cajon " + u.getCajon() : "Sin cajon";
                ElejirCajon.addItem(cajon);
            }
        }
    }//GEN-LAST:event_ElejirArmarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaBusqueda busqueda = new VentanaBusqueda(new javax.swing.JFrame(), true);
                busqueda.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                busqueda.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Armario;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonPaginaWeb;
    private javax.swing.JLabel Cajon;
    private javax.swing.JLabel Categoria;
    private javax.swing.JComboBox<String> ElejirArmario;
    private javax.swing.JComboBox<String> ElejirCajon;
    private javax.swing.JComboBox<String> ElejirCategoria;
    private javax.swing.JComboBox<String> ElejirEstado;
    private javax.swing.JLabel MensageMaterialesEncontrados;
    private javax.swing.JTextField TextBusqueda;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
