/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz.menuPrincipal;

import devoluciones.devoluciones;
import interfaz.modificar.MenuModificar;
import java.awt.BorderLayout;
import viewFormularios.FormularioAltaMaterial;
import viewFormularios.VentanaBusqueda;


/**
 *
 * @author DAM119
 */
public class MenuPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipalAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botonConsulta = new javax.swing.JButton();
        botonLocalizacion = new javax.swing.JButton();
        botonPrestamos = new javax.swing.JButton();
        botonDevoluciones = new javax.swing.JButton();
        botonAlta = new javax.swing.JButton();
        botonBaja = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonInformes = new javax.swing.JButton();
        botonGestionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelDerecha = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(76, 76, 76));

        jPanel2.setBackground(new java.awt.Color(76, 76, 76));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));

        botonConsulta.setBackground(new java.awt.Color(51, 51, 51));
        botonConsulta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonConsulta.setForeground(new java.awt.Color(255, 255, 255));
        botonConsulta.setText("Consulta");
        botonConsulta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaActionPerformed(evt);
            }
        });

        botonLocalizacion.setBackground(new java.awt.Color(51, 51, 51));
        botonLocalizacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonLocalizacion.setForeground(new java.awt.Color(255, 255, 255));
        botonLocalizacion.setText("Localización");
        botonLocalizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonLocalizacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonLocalizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLocalizacionActionPerformed(evt);
            }
        });

        botonPrestamos.setBackground(new java.awt.Color(51, 51, 51));
        botonPrestamos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        botonPrestamos.setText("Préstamos");
        botonPrestamos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonPrestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrestamosActionPerformed(evt);
            }
        });

        botonDevoluciones.setBackground(new java.awt.Color(51, 51, 51));
        botonDevoluciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonDevoluciones.setForeground(new java.awt.Color(255, 255, 255));
        botonDevoluciones.setText("Devoluciones");
        botonDevoluciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonDevoluciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDevolucionesActionPerformed(evt);
            }
        });

        botonAlta.setBackground(new java.awt.Color(51, 51, 51));
        botonAlta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonAlta.setForeground(new java.awt.Color(255, 255, 255));
        botonAlta.setText("Alta");
        botonAlta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAltaActionPerformed(evt);
            }
        });

        botonBaja.setBackground(new java.awt.Color(51, 51, 51));
        botonBaja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonBaja.setForeground(new java.awt.Color(255, 255, 255));
        botonBaja.setText("Baja");
        botonBaja.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBajaActionPerformed(evt);
            }
        });

        botonModificar.setBackground(new java.awt.Color(51, 51, 51));
        botonModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonModificar.setForeground(new java.awt.Color(255, 255, 255));
        botonModificar.setText("Modificar datos");
        botonModificar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonInformes.setBackground(new java.awt.Color(51, 51, 51));
        botonInformes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonInformes.setForeground(new java.awt.Color(255, 255, 255));
        botonInformes.setText("Informes");
        botonInformes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonInformes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInformesActionPerformed(evt);
            }
        });

        botonGestionar.setBackground(new java.awt.Color(51, 51, 51));
        botonGestionar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonGestionar.setForeground(new java.awt.Color(255, 255, 255));
        botonGestionar.setText("Gestionar ubicación");
        botonGestionar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonGestionar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonGestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGestionar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(botonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonGestionar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrador");

        panelDerecha.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(panelDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDerecha)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLocalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLocalizacionActionPerformed
        // TODO add your handling code here:
        
        VentanaBusqueda buscar = new VentanaBusqueda(this, true);
        buscar.setVisible(true);
        
        botonConsultaActionPerformed(null);
        
        panelDerecha.revalidate();
        panelDerecha.repaint();
        
    }//GEN-LAST:event_botonLocalizacionActionPerformed

    private void botonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaActionPerformed
        // TODO add your handling code here:

        PanelConsultaMateriales panel = new PanelConsultaMateriales();

        panelDerecha.setViewportView(panel);

    }//GEN-LAST:event_botonConsultaActionPerformed

    private void botonPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrestamosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonPrestamosActionPerformed

    private void botonDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevolucionesActionPerformed
        // TODO add your handling code here:
        
        devoluciones devolucion = new devoluciones(this,true);
        devolucion.setVisible(true);
        
        panelDerecha.revalidate();
        panelDerecha.repaint();
        
    }//GEN-LAST:event_botonDevolucionesActionPerformed

    private void botonInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInformesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInformesActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        // TODO add your handling code here:

        MenuModificar modificar = new MenuModificar(this, true);
        modificar.setVisible(true);

        //Llamamos al boton de consulta para refrescar la consulta a la base de datos
        botonConsultaActionPerformed(null);

        panelDerecha.revalidate(); // Re-calcula el diseño
        panelDerecha.repaint();    // Vuelve a pintar los píxeles

    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBajaActionPerformed
        //cogemos lo que ve el usuario en el panel
        java.awt.Component componenteActual = panelDerecha.getViewport().getView();
        
        //comprobamos si esta viendo la consulta de materiales
        if (componenteActual instanceof PanelConsultaMateriales) {
            PanelConsultaMateriales panelConsulta = (PanelConsultaMateriales) componenteActual;
            
            //cogemos el id de lo que selecciona
            int idSeleccionado = panelConsulta.getIdMaterialSeleccionado();
            
            //Si es -1 significa que no selecciona nada
            if (idSeleccionado == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Selecciona primero un material de la tabla para darlo de baja.", 
                    "Informacion", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            //pedimos confirmacion antes de dar de baja
            int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Estas seguro de que deseas dar de baja el material con ID: " + idSeleccionado, 
                "Confirmar Baja", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);
                
            if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
                //si da a si llamamos al metodo para cmabiar el estado a baja
                daoClasesSQL.MaterialDAO dao = new daoClasesSQL.MaterialDAO();
                boolean exito = dao.bajaMaterial(idSeleccionado);
                
                if (exito) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Material dado de baja correctamente.");
                    //actualizamos la tabla
                    panelConsulta.refrescarLsitado();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Hubo un error al intentar dar de baja el material.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Abre primero la pantalla de 'Consulta' y selecciona un material.", 
                "Informacion", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botonBajaActionPerformed

    private void botonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAltaActionPerformed

        //Abrimos la ventana de alta de material
        FormularioAltaMaterial altaMaterial = new FormularioAltaMaterial(this, true);
        altaMaterial.setVisible(true);
        //Llamamos al boton de consulta para refrescar la consulta a la base de datos
        botonConsultaActionPerformed(null);

        panelDerecha.revalidate(); // Re-calcula el diseño
        panelDerecha.repaint();    // Vuelve a pintar los píxeles

    }//GEN-LAST:event_botonAltaActionPerformed

    private void botonGestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGestionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAlta;
    private javax.swing.JButton botonBaja;
    private javax.swing.JButton botonConsulta;
    private javax.swing.JButton botonDevoluciones;
    private javax.swing.JButton botonGestionar;
    private javax.swing.JButton botonInformes;
    private javax.swing.JButton botonLocalizacion;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonPrestamos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane panelDerecha;
    // End of variables declaration//GEN-END:variables
}
