/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz.menuPrincipal;

import devolucionesYPrestamos.devoluciones;
import devolucionesYPrestamos.prestamos;
import java.awt.BorderLayout;
import viewFormularios.VentanaBusqueda;

/**
 * Ventana del menú principal para los usuarios con el rol de profesor. Limita
 * los accesos ocultando los botones de alta, baja, modificación e informes que
 * son de administrador.
 *
 * * @author Equipo4
 */
public class MenuPrincipalProfesor extends javax.swing.JFrame {

    private modelClasesTablas.Usuario userSesion;

    /**
     * Constructor que crea el menú principal del profesor e inicializa los
     * componentes de la interfaz.
     *
     * * @param usuarioLogin objeto con la sesión activa del profesor que se
     * acaba de loguear.
     */
    public MenuPrincipalProfesor(modelClasesTablas.Usuario usuarioLogin) {
        initComponents();

        // Guardamos el usuario que recibimos en nuestra variable global
        this.userSesion = usuarioLogin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botonConsulta = new javax.swing.JButton();
        botonLocalizacion = new javax.swing.JButton();
        botonPrestamos = new javax.swing.JButton();
        botonDevoluciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelDerecha = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(76, 76, 76));

        jPanel2.setBackground(new java.awt.Color(76, 76, 76));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        botonConsulta.setBackground(new java.awt.Color(51, 51, 51));
        botonConsulta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonConsulta.setForeground(new java.awt.Color(255, 255, 255));
        botonConsulta.setText("Consulta");
        botonConsulta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaActionPerformed(evt);
            }
        });

        botonLocalizacion.setBackground(new java.awt.Color(51, 51, 51));
        botonLocalizacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonLocalizacion.setForeground(new java.awt.Color(255, 255, 255));
        botonLocalizacion.setText("Localización");
        botonLocalizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonLocalizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLocalizacionActionPerformed(evt);
            }
        });

        botonPrestamos.setBackground(new java.awt.Color(51, 51, 51));
        botonPrestamos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        botonPrestamos.setText("Préstamos");
        botonPrestamos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrestamosActionPerformed(evt);
            }
        });

        botonDevoluciones.setBackground(new java.awt.Color(51, 51, 51));
        botonDevoluciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonDevoluciones.setForeground(new java.awt.Color(255, 255, 255));
        botonDevoluciones.setText("Devoluciones");
        botonDevoluciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDevolucionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(botonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Profesor");

        panelDerecha.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Lanza el cuadro modal para buscar los detalles de localización de las
     * herramientas del taller.
     *
     * * @param evt evento de acción al pulsar el botón localización.
     * @author alberto gonzalez
     */
    private void botonLocalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLocalizacionActionPerformed
        // TODO add your handling code here:
        VentanaBusqueda buscar = new VentanaBusqueda(this, true);
        buscar.setVisible(true);

        botonConsultaActionPerformed(null);

        panelDerecha.revalidate();
        panelDerecha.repaint();
    }//GEN-LAST:event_botonLocalizacionActionPerformed
    /**
     * Inyecta de forma dinámica el panel con la tabla de consulta de materiales
     * en el scrollpane derecho.
     *
     * * @param evt evento de acción al pulsar el botón consulta.
     * @author sergio camacho
     */
    private void botonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaActionPerformed
        // TODO add your handling code here:

        PanelConsultaMateriales panel = new PanelConsultaMateriales();

        panelDerecha.setViewportView(panel);

    }//GEN-LAST:event_botonConsultaActionPerformed
    /**
     * Abre el diálogo modal de préstamos pasando los parámetros de la sesión
     * activa del profesor.
     *
     * * @param evt evento de acción al pulsar el botón préstamos.
     * @author aday fernandez
     */
    private void botonPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrestamosActionPerformed
        // TODO add your handling code here:
        prestamos p = new prestamos(this, true, this.userSesion);
        p.setVisible(true);

        panelDerecha.revalidate();
        panelDerecha.repaint();
    }//GEN-LAST:event_botonPrestamosActionPerformed
    /**
     * Muestra la pantalla flotante de devoluciones para que el profesor cierre
     * sus entregas pendientes.
     *
     * * @param evt evento de acción al pulsar el botón devoluciones.
     * @author aday fernandez
     */
    private void botonDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevolucionesActionPerformed
        // TODO add your handling code here:
        devoluciones devolucion = new devoluciones(this, true);
        devolucion.setVisible(true);

        panelDerecha.revalidate();
        panelDerecha.repaint();
    }//GEN-LAST:event_botonDevolucionesActionPerformed

    /**
     * Método de arranque encargado de aplicar el Look and Feel de Nimbus e
     * iniciar el hilo visual del menú del profesor.
     *
     * * @param args argumentos de ejecución pasados por la consola del
     * sistema.
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Usuario de prueba para que el archivo no de error
                modelClasesTablas.Usuario uTest = new modelClasesTablas.Usuario();
                uTest.setNombre("Profesor Prueba");
                uTest.setRol("profesor");

                // Pasamos el usuario de prueba al constructor
                new MenuPrincipalProfesor(uTest).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsulta;
    private javax.swing.JButton botonDevoluciones;
    private javax.swing.JButton botonLocalizacion;
    private javax.swing.JButton botonPrestamos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane panelDerecha;
    // End of variables declaration//GEN-END:variables
}
