
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


# ==========================================
# CONFIGURACI\u00d3N DE LA BASE DE DATOS
# Cambia 'entorno' a 'local' o 'aws'
# ==========================================
entorno=aws

# --- CONEXI\u00d3N AWS ---
aws.url=jdbc:mysql://18.209.239.238:3306/inventario_taller
aws.user=admin
aws.pass=Grupo4

# --- CONEXI\u00d3N LOCAL (Para pruebas en tu PC) ---
# (Asumiendo que usas XAMPP o similar con usuario root sin clave)
local.url=jdbc:mysql://localhost:3306/inventario_taller
local.user=root
local.pass=